# a = int(input("Enter integer a:"))
# b = int(input("Enter integer b:"))
# print(f"sum:{a+b}")
# print(f"difference:{a-b}")
# print(f"multiplication:{a*b}")
# print(f"quotient :{a / b if b != 0 else'undefined'}")
# print(f"remainder :{a % b if b != 0 else 'undefined'}")
# a = int(input("Enter the number :"))
# b = int(input("enter the number :"))
# print(f"sum : {a+b}")
# print(f"difference :{a<b if a>=b  else 'undefined'}")
# print(f"product : {a*b}")
# print(f"quotient : {a/b if b !=0 else 'undefined' }")
# print(f"reminder : {a % b if b != 0 else 'undefined' }")
# a = int(input("Enter the first number:" )) 
# b = int(input("Enter the second number:"))
# print(f"sum:{a+b}")
# print(f"difference:{a-b}")
# print(f"product:{a*b}")
# print(f"quotient:{a / b if b !=0 else 'undefined' }")
# print(f"reminder:{a % b if b !=0 else 'undefined'}")
a = 1
b = 2
print("quotient:{a / b if b !=0 else'undefined'}")
print("reminder:{a % b if b !=0 else 'undefined'}")
print("quotient : {a % b if b ! = 0 else 'undefined}")